/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DarshanBooking {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'confirmed' : null },
  'userId' : Principal,
  'date' : Time,
  'name' : string,
  'numberOfPersons' : bigint,
  'phone' : string,
  'timeSlot' : { 'morning' : null } |
    { 'evening' : null } |
    { 'afternoon' : null },
}
export interface Donation {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'email' : string,
  'paymentMode' : { 'cash' : null } |
    { 'online' : null },
  'phone' : string,
  'amount' : number,
  'purpose' : { 'education' : null } |
    { 'templeConstruction' : null } |
    { 'annaPrasad' : null } |
    { 'general' : null } |
    { 'cowProtection' : null },
  'transactionId' : [] | [string],
}
export interface RoomBooking {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'confirmed' : null },
  'checkIn' : Time,
  'userId' : Principal,
  'name' : string,
  'numberOfPersons' : bigint,
  'checkOut' : Time,
  'phone' : string,
  'roomType' : { 'dormitory' : null } |
    { 'double' : null } |
    { 'single' : null },
}
export interface SevaBooking {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'confirmed' : null },
  'userId' : Principal,
  'date' : Time,
  'name' : string,
  'sevaType' : { 'aarti' : null } |
    { 'havan' : null } |
    { 'puja' : null } |
    { 'archana' : null } |
    { 'abhishek' : null },
  'phone' : string,
  'amount' : number,
}
export type Time = bigint;
export interface User {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonation' : ActorMethod<[Donation], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDarshanBooking' : ActorMethod<[DarshanBooking], bigint>,
  'createRoomBooking' : ActorMethod<[RoomBooking], bigint>,
  'createSevaBooking' : ActorMethod<[SevaBooking], bigint>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllActiveDarshanBookings' : ActorMethod<[], Array<DarshanBooking>>,
  'getAllActiveDonations' : ActorMethod<[], Array<Donation>>,
  'getAllActiveRoomBookings' : ActorMethod<[], Array<RoomBooking>>,
  'getAllActiveSevaBookings' : ActorMethod<[], Array<SevaBooking>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDarshanBooking' : ActorMethod<[bigint], DarshanBooking>,
  'getDonation' : ActorMethod<[bigint], Donation>,
  'getRoomBooking' : ActorMethod<[bigint], RoomBooking>,
  'getSevaBooking' : ActorMethod<[bigint], SevaBooking>,
  'getUser' : ActorMethod<[Principal], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string, string], Principal>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDarshanBookings' : ActorMethod<[string], Array<DarshanBooking>>,
  'searchDonations' : ActorMethod<[string], Array<Donation>>,
  'searchRoomBookings' : ActorMethod<[string], Array<RoomBooking>>,
  'searchSevaBookings' : ActorMethod<[string], Array<SevaBooking>>,
  'updateDarshanBookingStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updateRoomBookingStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updateSevaBookingStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];