/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'paymentMode' : IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null }),
  'phone' : IDL.Text,
  'amount' : IDL.Float64,
  'purpose' : IDL.Variant({
    'education' : IDL.Null,
    'templeConstruction' : IDL.Null,
    'annaPrasad' : IDL.Null,
    'general' : IDL.Null,
    'cowProtection' : IDL.Null,
  }),
  'transactionId' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DarshanBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'date' : Time,
  'name' : IDL.Text,
  'numberOfPersons' : IDL.Nat,
  'phone' : IDL.Text,
  'timeSlot' : IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'afternoon' : IDL.Null,
  }),
});
export const RoomBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'checkIn' : Time,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'numberOfPersons' : IDL.Nat,
  'checkOut' : Time,
  'phone' : IDL.Text,
  'roomType' : IDL.Variant({
    'dormitory' : IDL.Null,
    'double' : IDL.Null,
    'single' : IDL.Null,
  }),
});
export const SevaBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'date' : Time,
  'name' : IDL.Text,
  'sevaType' : IDL.Variant({
    'aarti' : IDL.Null,
    'havan' : IDL.Null,
    'puja' : IDL.Null,
    'archana' : IDL.Null,
    'abhishek' : IDL.Null,
  }),
  'phone' : IDL.Text,
  'amount' : IDL.Float64,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonation' : IDL.Func([Donation], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDarshanBooking' : IDL.Func([DarshanBooking], [IDL.Nat], []),
  'createRoomBooking' : IDL.Func([RoomBooking], [IDL.Nat], []),
  'createSevaBooking' : IDL.Func([SevaBooking], [IDL.Nat], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllActiveDarshanBookings' : IDL.Func(
      [],
      [IDL.Vec(DarshanBooking)],
      ['query'],
    ),
  'getAllActiveDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllActiveRoomBookings' : IDL.Func([], [IDL.Vec(RoomBooking)], ['query']),
  'getAllActiveSevaBookings' : IDL.Func([], [IDL.Vec(SevaBooking)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDarshanBooking' : IDL.Func([IDL.Nat], [DarshanBooking], ['query']),
  'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
  'getRoomBooking' : IDL.Func([IDL.Nat], [RoomBooking], ['query']),
  'getSevaBooking' : IDL.Func([IDL.Nat], [SevaBooking], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDarshanBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DarshanBooking)],
      ['query'],
    ),
  'searchDonations' : IDL.Func([IDL.Text], [IDL.Vec(Donation)], ['query']),
  'searchRoomBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RoomBooking)],
      ['query'],
    ),
  'searchSevaBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SevaBooking)],
      ['query'],
    ),
  'updateDarshanBookingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateRoomBookingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateSevaBookingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'paymentMode' : IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null }),
    'phone' : IDL.Text,
    'amount' : IDL.Float64,
    'purpose' : IDL.Variant({
      'education' : IDL.Null,
      'templeConstruction' : IDL.Null,
      'annaPrasad' : IDL.Null,
      'general' : IDL.Null,
      'cowProtection' : IDL.Null,
    }),
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DarshanBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'date' : Time,
    'name' : IDL.Text,
    'numberOfPersons' : IDL.Nat,
    'phone' : IDL.Text,
    'timeSlot' : IDL.Variant({
      'morning' : IDL.Null,
      'evening' : IDL.Null,
      'afternoon' : IDL.Null,
    }),
  });
  const RoomBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'checkIn' : Time,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'numberOfPersons' : IDL.Nat,
    'checkOut' : Time,
    'phone' : IDL.Text,
    'roomType' : IDL.Variant({
      'dormitory' : IDL.Null,
      'double' : IDL.Null,
      'single' : IDL.Null,
    }),
  });
  const SevaBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'date' : Time,
    'name' : IDL.Text,
    'sevaType' : IDL.Variant({
      'aarti' : IDL.Null,
      'havan' : IDL.Null,
      'puja' : IDL.Null,
      'archana' : IDL.Null,
      'abhishek' : IDL.Null,
    }),
    'phone' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonation' : IDL.Func([Donation], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDarshanBooking' : IDL.Func([DarshanBooking], [IDL.Nat], []),
    'createRoomBooking' : IDL.Func([RoomBooking], [IDL.Nat], []),
    'createSevaBooking' : IDL.Func([SevaBooking], [IDL.Nat], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllActiveDarshanBookings' : IDL.Func(
        [],
        [IDL.Vec(DarshanBooking)],
        ['query'],
      ),
    'getAllActiveDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllActiveRoomBookings' : IDL.Func(
        [],
        [IDL.Vec(RoomBooking)],
        ['query'],
      ),
    'getAllActiveSevaBookings' : IDL.Func(
        [],
        [IDL.Vec(SevaBooking)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDarshanBooking' : IDL.Func([IDL.Nat], [DarshanBooking], ['query']),
    'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
    'getRoomBooking' : IDL.Func([IDL.Nat], [RoomBooking], ['query']),
    'getSevaBooking' : IDL.Func([IDL.Nat], [SevaBooking], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDarshanBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DarshanBooking)],
        ['query'],
      ),
    'searchDonations' : IDL.Func([IDL.Text], [IDL.Vec(Donation)], ['query']),
    'searchRoomBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RoomBooking)],
        ['query'],
      ),
    'searchSevaBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SevaBooking)],
        ['query'],
      ),
    'updateDarshanBookingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateRoomBookingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateSevaBookingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };