/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donation {
    id: bigint;
    date: Time;
    name: string;
    email: string;
    paymentMode: Variant_cash_online;
    phone: string;
    amount: number;
    purpose: Variant_education_templeConstruction_annaPrasad_general_cowProtection;
    transactionId?: string;
}
export type Time = bigint;
export interface RoomBooking {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    checkIn: Time;
    userId: Principal;
    name: string;
    numberOfPersons: bigint;
    checkOut: Time;
    phone: string;
    roomType: Variant_dormitory_double_single;
}
export interface User {
    id: Principal;
    name: string;
    email: string;
    passwordHash: string;
    phone: string;
}
export interface DarshanBooking {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    numberOfPersons: bigint;
    phone: string;
    timeSlot: Variant_morning_evening_afternoon;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface SevaBooking {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    sevaType: Variant_aarti_havan_puja_archana_abhishek;
    phone: string;
    amount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_aarti_havan_puja_archana_abhishek {
    aarti = "aarti",
    havan = "havan",
    puja = "puja",
    archana = "archana",
    abhishek = "abhishek"
}
export enum Variant_cancelled_pending_confirmed {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum Variant_cash_online {
    cash = "cash",
    online = "online"
}
export enum Variant_dormitory_double_single {
    dormitory = "dormitory",
    double_ = "double",
    single = "single"
}
export enum Variant_education_templeConstruction_annaPrasad_general_cowProtection {
    education = "education",
    templeConstruction = "templeConstruction",
    annaPrasad = "annaPrasad",
    general = "general",
    cowProtection = "cowProtection"
}
export enum Variant_morning_evening_afternoon {
    morning = "morning",
    evening = "evening",
    afternoon = "afternoon"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonation(donation: Donation): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDarshanBooking(booking: DarshanBooking): Promise<bigint>;
    createRoomBooking(booking: RoomBooking): Promise<bigint>;
    createSevaBooking(booking: SevaBooking): Promise<bigint>;
    deleteUser(userId: Principal): Promise<void>;
    getAllActiveDarshanBookings(): Promise<Array<DarshanBooking>>;
    getAllActiveDonations(): Promise<Array<Donation>>;
    getAllActiveRoomBookings(): Promise<Array<RoomBooking>>;
    getAllActiveSevaBookings(): Promise<Array<SevaBooking>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDarshanBooking(id: bigint): Promise<DarshanBooking>;
    getDonation(id: bigint): Promise<Donation>;
    getRoomBooking(id: bigint): Promise<RoomBooking>;
    getSevaBooking(id: bigint): Promise<SevaBooking>;
    getUser(userId: Principal): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(name: string, email: string, phone: string, passwordHash: string): Promise<Principal>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDarshanBookings(term: string): Promise<Array<DarshanBooking>>;
    searchDonations(term: string): Promise<Array<Donation>>;
    searchRoomBookings(term: string): Promise<Array<RoomBooking>>;
    searchSevaBookings(term: string): Promise<Array<SevaBooking>>;
    updateDarshanBookingStatus(id: bigint, status: Variant_cancelled_pending_confirmed): Promise<void>;
    updateRoomBookingStatus(id: bigint, status: Variant_cancelled_pending_confirmed): Promise<void>;
    updateSevaBookingStatus(id: bigint, status: Variant_cancelled_pending_confirmed): Promise<void>;
}
import type { DarshanBooking as _DarshanBooking, Donation as _Donation, RoomBooking as _RoomBooking, SevaBooking as _SevaBooking, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonation(arg0: Donation): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonation(to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonation(to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDarshanBooking(arg0: DarshanBooking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDarshanBooking(to_candid_DarshanBooking_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDarshanBooking(to_candid_DarshanBooking_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRoomBooking(arg0: RoomBooking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoomBooking(to_candid_RoomBooking_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoomBooking(to_candid_RoomBooking_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSevaBooking(arg0: SevaBooking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSevaBooking(to_candid_SevaBooking_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSevaBooking(to_candid_SevaBooking_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllActiveDarshanBookings(): Promise<Array<DarshanBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveDarshanBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveDarshanBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveDonations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveDonations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveRoomBookings(): Promise<Array<RoomBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveRoomBookings();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveRoomBookings();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveSevaBookings(): Promise<Array<SevaBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveSevaBookings();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveSevaBookings();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDarshanBooking(arg0: bigint): Promise<DarshanBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getDarshanBooking(arg0);
                return from_candid_DarshanBooking_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDarshanBooking(arg0);
            return from_candid_DarshanBooking_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonation(arg0: bigint): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonation(arg0);
                return from_candid_Donation_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonation(arg0);
            return from_candid_Donation_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomBooking(arg0: bigint): Promise<RoomBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomBooking(arg0);
                return from_candid_RoomBooking_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomBooking(arg0);
            return from_candid_RoomBooking_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSevaBooking(arg0: bigint): Promise<SevaBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getSevaBooking(arg0);
                return from_candid_SevaBooking_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSevaBooking(arg0);
            return from_candid_SevaBooking_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchDarshanBookings(arg0: string): Promise<Array<DarshanBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDarshanBookings(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDarshanBookings(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchDonations(arg0: string): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonations(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonations(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchRoomBookings(arg0: string): Promise<Array<RoomBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRoomBookings(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRoomBookings(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchSevaBookings(arg0: string): Promise<Array<SevaBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSevaBookings(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSevaBookings(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDarshanBookingStatus(arg0: bigint, arg1: Variant_cancelled_pending_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDarshanBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDarshanBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRoomBookingStatus(arg0: bigint, arg1: Variant_cancelled_pending_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSevaBookingStatus(arg0: bigint, arg1: Variant_cancelled_pending_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSevaBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSevaBookingStatus(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DarshanBooking_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DarshanBooking): DarshanBooking {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RoomBooking_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomBooking): RoomBooking {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SevaBooking_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SevaBooking): SevaBooking {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    userId: Principal;
    date: _Time;
    name: string;
    numberOfPersons: bigint;
    phone: string;
    timeSlot: {
        morning: null;
    } | {
        evening: null;
    } | {
        afternoon: null;
    };
}): {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    numberOfPersons: bigint;
    phone: string;
    timeSlot: Variant_morning_evening_afternoon;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        name: value.name,
        numberOfPersons: value.numberOfPersons,
        phone: value.phone,
        timeSlot: from_candid_variant_n21(_uploadFile, _downloadFile, value.timeSlot)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    name: string;
    email: string;
    paymentMode: {
        cash: null;
    } | {
        online: null;
    };
    phone: string;
    amount: number;
    purpose: {
        education: null;
    } | {
        templeConstruction: null;
    } | {
        annaPrasad: null;
    } | {
        general: null;
    } | {
        cowProtection: null;
    };
    transactionId: [] | [string];
}): {
    id: bigint;
    date: Time;
    name: string;
    email: string;
    paymentMode: Variant_cash_online;
    phone: string;
    amount: number;
    purpose: Variant_education_templeConstruction_annaPrasad_general_cowProtection;
    transactionId?: string;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        email: value.email,
        paymentMode: from_candid_variant_n25(_uploadFile, _downloadFile, value.paymentMode),
        phone: value.phone,
        amount: value.amount,
        purpose: from_candid_variant_n26(_uploadFile, _downloadFile, value.purpose),
        transactionId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    checkIn: _Time;
    userId: Principal;
    name: string;
    numberOfPersons: bigint;
    checkOut: _Time;
    phone: string;
    roomType: {
        dormitory: null;
    } | {
        double: null;
    } | {
        single: null;
    };
}): {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    checkIn: Time;
    userId: Principal;
    name: string;
    numberOfPersons: bigint;
    checkOut: Time;
    phone: string;
    roomType: Variant_dormitory_double_single;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        checkIn: value.checkIn,
        userId: value.userId,
        name: value.name,
        numberOfPersons: value.numberOfPersons,
        checkOut: value.checkOut,
        phone: value.phone,
        roomType: from_candid_variant_n31(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    userId: Principal;
    date: _Time;
    name: string;
    sevaType: {
        aarti: null;
    } | {
        havan: null;
    } | {
        puja: null;
    } | {
        archana: null;
    } | {
        abhishek: null;
    };
    phone: string;
    amount: number;
}): {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    sevaType: Variant_aarti_havan_puja_archana_abhishek;
    phone: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        name: value.name,
        sevaType: from_candid_variant_n35(_uploadFile, _downloadFile, value.sevaType),
        phone: value.phone,
        amount: value.amount
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): Variant_cancelled_pending_confirmed {
    return "cancelled" in value ? Variant_cancelled_pending_confirmed.cancelled : "pending" in value ? Variant_cancelled_pending_confirmed.pending : "confirmed" in value ? Variant_cancelled_pending_confirmed.confirmed : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
}): Variant_morning_evening_afternoon {
    return "morning" in value ? Variant_morning_evening_afternoon.morning : "evening" in value ? Variant_morning_evening_afternoon.evening : "afternoon" in value ? Variant_morning_evening_afternoon.afternoon : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    online: null;
}): Variant_cash_online {
    return "cash" in value ? Variant_cash_online.cash : "online" in value ? Variant_cash_online.online : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    education: null;
} | {
    templeConstruction: null;
} | {
    annaPrasad: null;
} | {
    general: null;
} | {
    cowProtection: null;
}): Variant_education_templeConstruction_annaPrasad_general_cowProtection {
    return "education" in value ? Variant_education_templeConstruction_annaPrasad_general_cowProtection.education : "templeConstruction" in value ? Variant_education_templeConstruction_annaPrasad_general_cowProtection.templeConstruction : "annaPrasad" in value ? Variant_education_templeConstruction_annaPrasad_general_cowProtection.annaPrasad : "general" in value ? Variant_education_templeConstruction_annaPrasad_general_cowProtection.general : "cowProtection" in value ? Variant_education_templeConstruction_annaPrasad_general_cowProtection.cowProtection : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dormitory: null;
} | {
    double: null;
} | {
    single: null;
}): Variant_dormitory_double_single {
    return "dormitory" in value ? Variant_dormitory_double_single.dormitory : "double" in value ? Variant_dormitory_double_single.double : "single" in value ? Variant_dormitory_double_single.single : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aarti: null;
} | {
    havan: null;
} | {
    puja: null;
} | {
    archana: null;
} | {
    abhishek: null;
}): Variant_aarti_havan_puja_archana_abhishek {
    return "aarti" in value ? Variant_aarti_havan_puja_archana_abhishek.aarti : "havan" in value ? Variant_aarti_havan_puja_archana_abhishek.havan : "puja" in value ? Variant_aarti_havan_puja_archana_abhishek.puja : "archana" in value ? Variant_aarti_havan_puja_archana_abhishek.archana : "abhishek" in value ? Variant_aarti_havan_puja_archana_abhishek.abhishek : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DarshanBooking>): Array<DarshanBooking> {
    return value.map((x)=>from_candid_DarshanBooking_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomBooking>): Array<RoomBooking> {
    return value.map((x)=>from_candid_RoomBooking_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SevaBooking>): Array<SevaBooking> {
    return value.map((x)=>from_candid_SevaBooking_n33(_uploadFile, _downloadFile, x));
}
function to_candid_DarshanBooking_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DarshanBooking): _DarshanBooking {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Donation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Donation): _Donation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RoomBooking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomBooking): _RoomBooking {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SevaBooking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SevaBooking): _SevaBooking {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    checkIn: Time;
    userId: Principal;
    name: string;
    numberOfPersons: bigint;
    checkOut: Time;
    phone: string;
    roomType: Variant_dormitory_double_single;
}): {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    checkIn: _Time;
    userId: Principal;
    name: string;
    numberOfPersons: bigint;
    checkOut: _Time;
    phone: string;
    roomType: {
        dormitory: null;
    } | {
        double: null;
    } | {
        single: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        checkIn: value.checkIn,
        userId: value.userId,
        name: value.name,
        numberOfPersons: value.numberOfPersons,
        checkOut: value.checkOut,
        phone: value.phone,
        roomType: to_candid_variant_n13(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    sevaType: Variant_aarti_havan_puja_archana_abhishek;
    phone: string;
    amount: number;
}): {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    userId: Principal;
    date: _Time;
    name: string;
    sevaType: {
        aarti: null;
    } | {
        havan: null;
    } | {
        puja: null;
    } | {
        archana: null;
    } | {
        abhishek: null;
    };
    phone: string;
    amount: number;
} {
    return {
        id: value.id,
        status: to_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        name: value.name,
        sevaType: to_candid_variant_n16(_uploadFile, _downloadFile, value.sevaType),
        phone: value.phone,
        amount: value.amount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: Time;
    name: string;
    email: string;
    paymentMode: Variant_cash_online;
    phone: string;
    amount: number;
    purpose: Variant_education_templeConstruction_annaPrasad_general_cowProtection;
    transactionId?: string;
}): {
    id: bigint;
    date: _Time;
    name: string;
    email: string;
    paymentMode: {
        cash: null;
    } | {
        online: null;
    };
    phone: string;
    amount: number;
    purpose: {
        education: null;
    } | {
        templeConstruction: null;
    } | {
        annaPrasad: null;
    } | {
        general: null;
    } | {
        cowProtection: null;
    };
    transactionId: [] | [string];
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        email: value.email,
        paymentMode: to_candid_variant_n3(_uploadFile, _downloadFile, value.paymentMode),
        phone: value.phone,
        amount: value.amount,
        purpose: to_candid_variant_n4(_uploadFile, _downloadFile, value.purpose),
        transactionId: value.transactionId ? candid_some(value.transactionId) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_cancelled_pending_confirmed;
    userId: Principal;
    date: Time;
    name: string;
    numberOfPersons: bigint;
    phone: string;
    timeSlot: Variant_morning_evening_afternoon;
}): {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    userId: Principal;
    date: _Time;
    name: string;
    numberOfPersons: bigint;
    phone: string;
    timeSlot: {
        morning: null;
    } | {
        evening: null;
    } | {
        afternoon: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        name: value.name,
        numberOfPersons: value.numberOfPersons,
        phone: value.phone,
        timeSlot: to_candid_variant_n10(_uploadFile, _downloadFile, value.timeSlot)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_morning_evening_afternoon): {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
} {
    return value == Variant_morning_evening_afternoon.morning ? {
        morning: null
    } : value == Variant_morning_evening_afternoon.evening ? {
        evening: null
    } : value == Variant_morning_evening_afternoon.afternoon ? {
        afternoon: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dormitory_double_single): {
    dormitory: null;
} | {
    double: null;
} | {
    single: null;
} {
    return value == Variant_dormitory_double_single.dormitory ? {
        dormitory: null
    } : value == Variant_dormitory_double_single.double ? {
        double_: null
    } : value == Variant_dormitory_double_single.single ? {
        single: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_aarti_havan_puja_archana_abhishek): {
    aarti: null;
} | {
    havan: null;
} | {
    puja: null;
} | {
    archana: null;
} | {
    abhishek: null;
} {
    return value == Variant_aarti_havan_puja_archana_abhishek.aarti ? {
        aarti: null
    } : value == Variant_aarti_havan_puja_archana_abhishek.havan ? {
        havan: null
    } : value == Variant_aarti_havan_puja_archana_abhishek.puja ? {
        puja: null
    } : value == Variant_aarti_havan_puja_archana_abhishek.archana ? {
        archana: null
    } : value == Variant_aarti_havan_puja_archana_abhishek.abhishek ? {
        abhishek: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cash_online): {
    cash: null;
} | {
    online: null;
} {
    return value == Variant_cash_online.cash ? {
        cash: null
    } : value == Variant_cash_online.online ? {
        online: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_education_templeConstruction_annaPrasad_general_cowProtection): {
    education: null;
} | {
    templeConstruction: null;
} | {
    annaPrasad: null;
} | {
    general: null;
} | {
    cowProtection: null;
} {
    return value == Variant_education_templeConstruction_annaPrasad_general_cowProtection.education ? {
        education: null
    } : value == Variant_education_templeConstruction_annaPrasad_general_cowProtection.templeConstruction ? {
        templeConstruction: null
    } : value == Variant_education_templeConstruction_annaPrasad_general_cowProtection.annaPrasad ? {
        annaPrasad: null
    } : value == Variant_education_templeConstruction_annaPrasad_general_cowProtection.general ? {
        general: null
    } : value == Variant_education_templeConstruction_annaPrasad_general_cowProtection.cowProtection ? {
        cowProtection: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_confirmed): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == Variant_cancelled_pending_confirmed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_confirmed.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
